name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # DO NOT REMOVE THE STEP BELOW, TESTIM CLI IS INCOMPATIBLE WITH NEWER PNPM VERSIONS
      - name: specify pnpm version
        uses: pnpm/action-setup@v2
        with:
          version: 8 

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Install dependencies and build
        run: |
          pnpm i
          pnpm run build:staging
          ls -a
          touch .env.staging
          echo "VITE_NODE_ENV=staging" >> .env.staging
          ls -a
          echo cat env !!!!
          cat .env.staging

      - name: Run Unit Tests
        run: pnpm run coverage

      - name: Deploy to Firebase Hosting (Staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODO_LIST_STAGING }}"
          channelId: live
          projectId: todo-list-staging

      # - name: Run Visual Regression Tests
      #   run: |
      #     pnpm add -g @testim/testim-cli --force
      #     testim --token ${{ secrets.TESTIM_TOKEN }} --project ${{ secrets.TESTIM_PROJECT_ID }} --grid "Testim-Grid"

      # - name: Deploy to Firebase Hosting (Production)
      #   if: github.ref == 'refs/heads/main'
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: "${{ secrets.GITHUB_TOKEN }}"
      #     firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODO_LIST_82592 }}"
      #     channelId: live
      #     projectId: todo-list-82592